config/routes.rb
Tinkuy::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount Koudoku::Engine, at: 'members'
  scope module: 'koudoku' do
    get 'membership' => 'subscriptions#index', as: 'membership'
  end

  namespace :admin do
    get '/' => 'events#index'
    resources :users do
      get '/delete_subscription' => "users#delete_subscription"
    end
    resources :events
    resources :plans
    resources :centers
    resources :memberships
    resources :resources do
      resources :timeslots do
        member do
          put :toggle_booking
        end
      end
    end

  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    get '/events' => "users#events"
    get '/display_therapist' => "users#display_therapist"
  end

  resources :resources do
    resources :timeslots do
      resources :bookings
    end
  end

  resources :recurring_bookings

  resources :events do
    member {
      post :upvote
    }
  end

  get '/suggestions' => 'events#suggestions'

  get '/info' => 'pages#info'
  get '/faq' => 'pages#faq'
  get '/bliv_medlem' => 'pages#bliv_medlem'

  namespace :api do
    resources :users
  end

  root :to => "pages#bliv_medlem"

end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  center_id        :integer
#  created_at       :datetime
#  updated_at       :datetime
#  max_members      :integer
#  price            :integer
#  fruits_per_month :integer          default(0)
#

class Membership < ActiveRecord::Base

  belongs_to :center
  
  has_many :users
  
  has_one :plan

end

app/controllers/admin/memberships_controller.rb
class Admin::MembershipsController < Admin::BaseController
  before_action :set_membership, only: [:edit, :update, :destroy]
  
  def index
    @memberships = Membership.all.order(:id)
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(membership_params)
    if @membership.save
      redirect_to admin_memberships_path, notice: 'Medlemskabet blev oprettet'
    else
      render action: 'new'
    end

  end

  def edit

  end

  def update
    if @membership.update(membership_params)
      redirect_to admin_memberships_path, notice: 'Medlemsskabet blev opdateret.'
      
    else
      render action: 'edit'
    
    end
  end

  def destroy
    @membership.destroy
    redirect_to admin_memberships_path, notice: 'Medlemskabet blev slettet' 
  end

  
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:id, :name, :center_id, :max_members, :price, :fruits_per_month)
    end
end

app/views/admin/memberships/_form.html.haml
= simple_form_for [:admin, @membership], :html => {:role => 'form' } do |f|
  = f.error_notification

  .form-inputs
    .row
      .col-md-6
        = f.association :center, :collection => Center.all, :label_method => :name, :value_method => :id
        = f.input :name
        = f.input :max_members
        = f.input :price
        = f.input :fruits_per_month
        -# = f.input :category, :collection => Category.all.order(:name), :label_method => :name, :value_method => :name, :input_html => { :class => "radio" }, as: :radio_buttons
        
  .form-actions
    = f.button :submit

app/views/admin/memberships/edit.html.haml
%h1 Ret medlemsskab

= render 'form'

= link_to 'Back', admin_memberships_path

app/views/admin/memberships/index.html.haml
.row
  .col-md-12
    %h1 Medlemsskaber
  - @memberships.each do |membership|
    .col-md-3
      .well
        %h4= membership.name
        %p
          - if membership.center.present?
            = membership.center.name
          - else 
            Center ikke tildelt
        
        %p
          - if membership.plan.present?
            %strong Plan:
            = membership.plan.name
          - else
            Plan ikke tildelt

        %hr/

        = link_to 'Edit', edit_admin_membership_path(membership), :class => 'btn btn-default'
        = link_to 'Destroy', admin_membership_path(membership), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger'

  .col-md-12
    = link_to 'Ny plan', new_admin_membership_path

app/views/admin/memberships/new.html.haml
%h1 Opret nyt medlemsskab

= render 'form'

= link_to 'Back', admin_memberships_path