config/routes.rb
Tinkuy::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount Koudoku::Engine, at: 'members'
  scope module: 'koudoku' do
    get 'membership' => 'subscriptions#index', as: 'membership'
  end

  namespace :admin do
    get '/' => 'events#index'
    resources :users do
      get '/delete_subscription' => "users#delete_subscription"
    end
    resources :events
    resources :plans
    resources :centers
    resources :memberships
    resources :resources do
      resources :timeslots do
        member do
          put :toggle_booking
        end
      end
    end

  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    get '/events' => "users#events"
    get '/display_therapist' => "users#display_therapist"
  end

  resources :resources do
    resources :timeslots do
      resources :bookings
    end
  end

  resources :recurring_bookings

  resources :events do
    member {
      post :upvote
    }
  end

  get '/suggestions' => 'events#suggestions'

  get '/info' => 'pages#info'
  get '/faq' => 'pages#faq'
  get '/bliv_medlem' => 'pages#bliv_medlem'

  namespace :api do
    resources :users
  end

  root :to => "pages#bliv_medlem"

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :text
#  starttime    :time
#  week_number  :integer
#  created_at   :datetime
#  updated_at   :datetime
#  startdate    :date
#  duration     :integer
#  hour         :integer
#  minute       :integer
#  confirmed    :boolean          default(FALSE)
#  user_id      :integer
#  fruits_count :integer
#  max_spaces   :integer
#  free_spaces  :integer
#

class Event < ActiveRecord::Base
  validates :startdate, :presence => true
  validates :starttime, :presence => true
  validates :user_id, :presence => true
  
  belongs_to :user

  has_many :votes, :dependent => :destroy
  has_many :bids, :dependent => :destroy
  
  has_one :fruitbasket, as: :owner

  def week_number
    startdate.beginning_of_week(start_day = :monday).strftime("%V").to_i
  end

  def user_name

    if user.present?
      firstname, surname = '', ''
      if user.firstname.present?
        firstname = user.firstname
      end

      if user.surname.present?
        surname = ' ' + user.surname
      end
      return (firstname + surname).strip()
    else
      return 'NO OWNER'
    end
    
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :set_event, only: [:edit, :update, :destroy]

  def index
    events = Event.includes(:fruitbasket).includes(:votes).order(startdate: :asc, starttime: :asc)
    @confirmed_events = events.where(:confirmed => true)
    
    if params[:old] == 'yes'
      @confirmed_events = @confirmed_events.where("startdate < ?", Date.today)
    else
      @confirmed_events = @confirmed_events.where("startdate >= ?", Date.today)
    end
    
    @unconfirmed_events = events.where(:confirmed => false).where("startdate >= ?", Date.today)
  end

  # GET /events/1/edit
  def edit
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_events_path, notice: 'Aktiviteten er nu blevet opdateret.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_path , notice: "Aktiviteten er nu slettet."}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :duration, :starttime, :startdate, :confirmed, :user_id)
    end  

end

app/controllers/events_controller.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :text
#  starttime    :time
#  week_number  :integer
#  created_at   :datetime
#  updated_at   :datetime
#  startdate    :date
#  duration     :integer
#  hour         :integer
#  minute       :integer
#  confirmed    :boolean          default(FALSE)
#  user_id      :integer
#  fruits_count :integer
#  max_spaces   :integer
#  free_spaces  :integer
#

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :get_permission, only: [:new, :edit, :update, :destroy, :upvote]
  before_filter :get_dates

  # GET /events
  # GET /events.json
  def index
    if session[:event_id].present?
      @new_event = Event.find(session[:event_id])
      session[:event_id] = nil
    end
    @events = Event.where(:confirmed => true).order(startdate: :asc, starttime: :asc)

    if params[:dato].present?
      session[:dato] = params[:dato].to_date
    end
    session[:next] = session[:dato] + 7.days
    session[:prev] = session[:dato] - 7.days

    @unconfirmed_events = Event.where(:confirmed => false).order(startdate: :asc, starttime: :asc)
    @top_events = Event.where(:confirmed => false).where("startdate >= ?", Date.today).order(fruits_count: :desc).limit(10)
    # @top_events = Event.joins(:fruits).group("fruits.event_id").order("count(fruits.event_id) desc").limit(10)

  end

  def suggestions
    # @events = Event.where(:confirmed => false).where("startdate >= ?", Date.today).order(fruits_count: :desc)
    @events = Event.where(:confirmed => false).where("startdate >= ?", Date.today).order(startdate: :asc)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @top_events = Event.where(:confirmed => false).where("startdate >= ?", Date.today).order(fruits_count: :desc).limit(10)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  
  def edit
  end

  
  def create
    @event = Event.new(event_params)

    if @event.save
      session[:event_id] = @event.id
      redirect_to events_path
    else
      render action: 'new'
    end
  end


  def update
    if @event.update(event_params)
      redirect_to events_path, notice: 'Aktiviteten er nu blevet opdateret.'
    else
      render action: 'edit'
    end
  end


  def destroy
    @event.destroy
    redirect_to :back, notice: "Aktiviteten er slettet"
  end

  def upvote
    @event = Event.find(params[:id])

    unless current_user.has_voted_on(@event)
      @vote = Vote.create(:event_id => @event.id, :user_id => current_user.id)
      @vote.save!
      redirect_to :back, notice: "Tak for din stemme!"
    else
      redirect_to :back, notice: "Du har allerede stemt"
    end
  end

  def get_dates
    session[:dato] = Date.today.beginning_of_week

    unless session[:is_new].present?
      session[:week_number] = Time.now.strftime("%V").to_i
    end
    session[:is_new] = "nej"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :duration, :starttime, :startdate, :hour, :minute, :user_id, :confirmed)
      # params.require(:event).permit!
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
# == Schema Information
#
# Table name: events
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :text
#  starttime    :time
#  week_number  :integer
#  created_at   :datetime
#  updated_at   :datetime
#  startdate    :date
#  duration     :integer
#  hour         :integer
#  minute       :integer
#  confirmed    :boolean          default(FALSE)
#  user_id      :integer
#  fruits_count :integer
#  max_spaces   :integer
#  free_spaces  :integer
#

module EventsHelper

  

end

app/views/events/_events_header.html.haml
.jumbotron.page
  .container
    .row
      .col-md-8
        %h1.page
          Aktiviteter
      .col-md-4
        - unless current_user
          - if @places_left
            = link_to membership_path, :class => "btn btn-success btn-signup btn-signup-small" do            
              Bliv medlem nu
              %i.fa.fa-chevron-circle-right

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg
  
  .form-group
    - if current_user.present?
      - if current_user.admin?
        .well.well-sm
          .row
            .col-md-12
              .label.label-success
                ADMIN OPTIONS
            .col-md-6
              = f.input :confirmed, :as => :radio_buttons, :label => "Gør aktiviteten aktuel", :include_blank => false
            .col-md-6
              = f.input :user_id, :collection => User.all.order(:firstname), :label_method => lambda {|user| "#{user.firstname} #{user.surname}"}, :value_method => :id, :include_blank => false, :label => "Admin af aktivitet", :selected => current_user.id
      - else
        = f.hidden_field :user_id, :value => current_user.id
    = f.input :name, :label => "Navn på aktivitet"
  .form-group
    .row
      .col-md-6
        .form-group
          %label 
            Dato
          .form-group
            #datetimepicker_date.input-group.date
              - if @event.startdate?
                = f.text_field :startdate, :class => 'form-control', :type => "text", "data-date-format" => "YYYY-MM-DD", :value => nice_date_format(@event.startdate), disabled: !current_user.admin?
              - else
                = f.text_field :startdate, :class => 'form-control', "data-date-format" => "YYYY-MM-DD", :type => "text"
              %span.input-group-addon
                %i.fa.fa-calendar-o
            :javascript
              $(function () {
                $('#datetimepicker_date').datetimepicker({
                  locale: 'dk',
                  useCurrent: true,
                  pickTime: false
                });
              });
            %p.help-block
              Vælg dato for aktivitet
      .col-md-6
        .form-group
          %label 
            Tidspunkt for start
          #datetimepicker_time.input-group.date
            - if @event.starttime?
              = f.text_field :starttime, :class => 'date form_time form-control', "date-date-format" => "DD/MM/YYYY HH/MM", :value => nice_time_format(@event.starttime), disabled: !current_user.admin?
            - else
              = f.text_field :starttime, :class => 'date form_time form-control', "date-date-format" => "DD/MM/YYYY HH/MM"
            %span.input-group-addon
              %i.fa.fa-clock-o
          :javascript
            $(function () {
              $('#datetimepicker_time').datetimepicker({
                format: 'HH:mm',
                pickDate: false,
                pickSeconds: false,
                pick12HourFormat: false,
                locale: 'dk',
                minuteStepping: 30,
                useCurrent: true,
              });
            });
          %p.help-block
            Skriv tidspunkt (fx. 10:30)
  .form-group
    = f.input :duration, :label => "Varighed (minutter)"
  .form-group
    = f.input :description, :label => "Beskrivelse"

  .actions
    = f.submit "Opret", :class => "btn btn-primary"

app/views/events/_list_events.html.haml
- @events.each do |event|
  - if event.startdate.wday == week_day && event.week_number == session[:dato].cweek and event.startdate.year == session[:dato].year
    = link_to event_path(event) do
      .well.well-sm.well-event
        %p
          %strong= event.starttime.strftime("%H:%M")
        %p
          = event.name
    .well.well-sm.well-event-admin
      %p
        %small
          - if event.user.present?
            = event.user.firstname
            - if current_user and event.user == (current_user or current_user.admin?)
              = link_to edit_event_path(event) do
                %i.fa.fa-pencil
          - else
            Admin
            - if current_user and current_user.admin?
              = link_to edit_event_path(event) do
                %i.fa.fa-pencil

app/views/events/_show_event.html.haml
#event-show-stuff
  .modal-header
    %button.close{"data-dismiss" => "modal", :type => "button"}
      %span{"aria-hidden" => "true"} &times;
      %span.sr-only Close
    %h4#myModalLabel.modal-title
      = @event.name
  .modal-body
    %table
      %tr
        %td
          %strong Dato:
          = @event.startdate.strftime("%A %-d. %b, %Y")
        %td
          %strong Tidspunkt:
          - if @event.starttime?
            = @event.starttime.strftime("%H:%M")
        %td
          %strong Varighed:
          - if @event.duration
            = @event.duration
            min
          - else
            Uoplyst     
    %hr/
    - unless @event.confirmed?
      .alert.alert-success
        %strong Bemærk: 
        Dette er en foreslået aktivitet. Det er endnu ikke aktuelt.
      %br/

    %h4
      Beskrivelse
    %p
      = @event.description.gsub(/\n/, '<br />').html_safe
  .modal-footer
    %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Luk

app/views/events/_top10.html.haml
.well.well-small
  %h4
    Top 10 foreslåede aktiviteter
  %small Disse aktiviteter er endnu ikke kommet  i kalenderen. Vis din interesse for aktiviteten ved at trykke på "Stem op"
  %hr/
  %ul.list-unstyled.top-events
    - @top_events.each do |event|
      %li.top-event
        .event-score
          .fruit-score
            = event.votes.count
        .event-info
          = link_to event_path(event) do
            = event.name.capitalize
            - if current_user and current_user.admin = true
              = link_to edit_event_path(event) do
                %i.fa.fa-pencil
          %p
            - if event.startdate?
              %small.grey= event.startdate.strftime("%A d %e. %b")
            = link_to upvote_event_path(event), method: "post", :class => "btn btn-success btn-xs pull-right" do
              Stem op
              %i.fa.fa-thumbs-up
        .clearfix
  = link_to "Se alle", suggestions_path, :class => "btn btn-primary"

app/views/events/edit.html.haml
.container
  .row
    .col-md-8
      %h1
        = @event.name
      .well.well-sm
        = @event.startdate.strftime("%A den %e. %b, %Y - ")
        = @event.starttime.strftime("klokken %H:%M")

      = render 'form'
      = link_to 'Back', events_path

app/views/events/index.html.haml
= render :partial => "events_header"
.container
  .row
    .col-md-8
      - if @event.present?
        = @event.name
      %h4.pull-left
        Uge
        = session[:dato].strftime('%V - %B, %Y')
      .pull-right
        = link_to new_event_path, :class => "btn btn-primary" do
          Foreslå ny aktivitet
        = link_to events_path(:dato => "#{session[:prev]}"), :class => "btn btn-default" do
          %i.fa.fa-angle-left
          Forrige uge
        = link_to events_path(:dato => "#{session[:next]}"), :class => "btn btn-default" do
          Næste uge
          %i.fa.fa-angle-right
        
        
      .clearfix
      .row
        .col-md-8
          %a.pull-left{:href => "/faq#tilmelding"}
            Hvordan tilmelder jeg mig aktiviterne?

      %hr/
      .row      
        .col-md-3
          %h4.day-of-week
            Mandag
            %small= "(#{session[:dato].strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 1, :events => @events}
        .col-md-3
          %h4.day-of-week
            Tirsdag
            %small= "(#{(session[:dato]+1).strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 2, :events => @events}
        .col-md-3
          %h4.day-of-week
            Onsdag
            %small= "(#{(session[:dato]+2).strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 3, :events => @events}
        .col-md-3
          %h4.day-of-week
            Torsdag
            %small= "(#{(session[:dato]+3).strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 4, :events => @events}
      .row
        .col-md-3
          %h4.day-of-week
            Fredag
            %small= "(#{(session[:dato]+4).strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 5, :events => @events}
        .col-md-3
          %h4.day-of-week
            Lørdag
            %small= "(#{(session[:dato]+5).strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 6, :events => @events}
        .col-md-3
          %h4.day-of-week
            Søndag
            %small= "(#{(session[:dato]+6).strftime('%-d. %b')})"
          = render :partial => "list_events", :locals => {:week_day => 0, :events => @events}
        .col-md-12
          %hr/
          .pull-right
            = link_to new_event_path, :class => "btn btn-primary" do
              Foreslå ny aktivitet
            = link_to events_path(:dato => "#{session[:prev]}"), :class => "btn btn-default" do
              %i.fa.fa-angle-left
              Forrige uge
            = link_to events_path(:dato => "#{session[:next]}"), :class => "btn btn-default" do
              Næste uge
              %i.fa.fa-angle-right
            
    .col-md-4
      = render :partial => "top10", :locals => {:top_events => @top_events}

-# #ShowEvent.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
-#   .modal-dialog
-#     .modal-content

-# - if @new_event.present?
-#   #new_event.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
-#     .modal-dialog
-#       .modal-content
-#         .modal-header
-#           %button.close{"data-dismiss" => "modal", :type => "button"}
-#             %span{"aria-hidden" => "true"} &times;
-#             %span.sr-only Close
-#           %h4#myModalLabel.modal-title
-#             - if @new_event.confirmed
-#               Ny aktivitet gemt
-#             - else
-#               Forslag til ny aktivitet gemt
-#         .modal-body
-#           %h4
-#             = @new_event.name
-#           %hr/
-#           %table
-#             %tr
-#               %td
-#                 %strong Dato:
-#                 = @new_event.startdate.strftime("%A %-d. %b, %Y")
-#               %td
-#                 %strong Tidspunkt:
-#                 - if @new_event.starttime?
-#                   = @new_event.starttime.strftime("%H:%M")
-#               %td
-#                 %strong Varighed:
-#                 - if @new_event.duration
-#                   = @new_event.duration
-#                   min
-#                 - else
-#                   Uoplyst     
-#           %hr/
-#           %h4
-#             Beskrivelse
-#           %p
-#             = @new_event.description.gsub(/\n/, '<br />').html_safe
-#         .modal-footer
-#           %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Luk

-#   :javascript
-#     $('#new_event').modal('show')

app/views/events/new.html.haml
= render :partial => "events_header"

.container
  .row
    .col-md-6
      %h2 Foreslå ny aktivitet

      = render 'form'
      = link_to 'Tilbage', :back
    .col-md-6
      %h2 Husk
      .well
        %h4 Når du ”foreslår ny aktivitet” beder vi dig huske: 
        %hr
        %ul
          %li Under ”Navn på aktiviteter” kan du efter ”titlen” skrive hvis den afholdes udenfor workshoprummet fx i loungen. Så kan andre workshopholdere nemt se at workshoprummet er ledigt. 
          %li Husk at notere varighed på aktiviteten under ”Varighed (minutter)”
          %li I beskrivelsen af din aktivitet under ”Beskrivelse” kan du udover beskrivelse skrive kontaktoplysninger til dig og hvad du ønsker i forhold til tilmelding/afmelding. Du kan med fordel indsætte link til facebook-event, hvis du opretter sådan et. 
          %li Er du i tvivl om noget, så skriv på info@tinkuy.dk eller spørg en af os, der har været i Tinkuy længe.

app/views/events/show.html.haml
= render :partial => "events_header"
.container
  .row
    .col-md-8
      %button{:onclick => "history.back()"} Tilbage
      %h2
        = @event.name

      %p
        %strong Tidspunkt:
        %span 
          = @event.startdate.strftime("%-d. %b., kl")
          = @event.starttime.strftime("%H:%M")
        %br
        %strong Varighed:
        %span
          = @event.duration
          minutter
        %br
        %strong Tovholder:
        %span
          = @event.user.firstname

      %p
        = @event.description.gsub(/\n/, '<br />').html_safe

      -# = link_to "Tilmeld", "", :class => 'btn btn-default'
      -# - if current_user
      -#   - simple_form_for :bid do

app/views/events/suggestions.html.haml
= render :partial => "events_header"

.container
  .row
    .col-md-8
      %h2 Foreslåede aktiviteter
      - @events.each do |event|
        .event-badge
          .title
            .info
              %h4= event.name
              %table
                %tr
                  %td
                    %strong Uge
                    = event.startdate.strftime("%W")
                  %td
                    %strong Dato
                    = event.startdate
                  %td
                    %strong Tidspunkt
                    = event.starttime.strftime("- %H:%M")
            .vote
              %span.score= event.votes.count
              = link_to upvote_event_path(event), method: "post", :class => "btn btn-success" do
                Stem op
                %i.fa.fa-thumbs-up
            .clearfix
          .description
            %p= event.description
      %hr/
      = link_to 'Foreslå ny aktivitet', new_event_path, :class => "btn btn-primary"
    .col-md-4
      = link_to 'Foreslå ny aktivitet', new_event_path, :class => "btn btn-primary"