config/routes.rb
Tinkuy::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount Koudoku::Engine, at: 'members'
  scope module: 'koudoku' do
    get 'membership' => 'subscriptions#index', as: 'membership'
  end

  namespace :admin do
    get '/' => 'events#index'
    resources :users do
      get '/delete_subscription' => "users#delete_subscription"
    end
    resources :events
    resources :plans
    resources :centers
    resources :memberships
    resources :resources do
      resources :timeslots do
        member do
          put :toggle_booking
        end
      end
    end

  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    get '/events' => "users#events"
    get '/display_therapist' => "users#display_therapist"
  end

  resources :resources do
    resources :timeslots do
      resources :bookings
    end
  end

  resources :recurring_bookings

  resources :events do
    member {
      post :upvote
    }
  end

  get '/suggestions' => 'events#suggestions'

  get '/info' => 'pages#info'
  get '/faq' => 'pages#faq'
  get '/bliv_medlem' => 'pages#bliv_medlem'

  namespace :api do
    resources :users
  end

  root :to => "pages#bliv_medlem"

end

app/views/admin/resources/_form.html.haml
= simple_form_for [:admin, @resource], :html => {:role => 'form' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :duration, :label => "Angiv tidsinterval for 'timeslots', fx. 2 "

  .form-actions
    = f.button :submit

app/views/admin/resources/edit.html.haml
%h1 Editing resource

= render 'form'

= link_to 'Show', @resource
\|
= link_to 'Back', resources_path

app/views/admin/resources/index.html.haml
%h1 Listing resources

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @resources.each do |resource|
    %tr
      %td= resource.name
      %td= resource.description
      %td= link_to 'Show', admin_resource_path(resource)
      %td= link_to 'Edit', edit_admin_resource_path(resource)
      %td= link_to 'Destroy', [:admin, resource], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Resource', new_admin_resource_path

app/views/admin/resources/new.html.haml
%h1 New resource

= render 'form'

= link_to 'Back', admin_resources_path

app/views/admin/resources/show.html.haml
%p#notice= notice

%h2
  = @resource.name
= link_to 'Edit', edit_resource_path(@resource)
\|
= link_to 'Back', resources_path


.row
  .col-md-8
    %h4.pull-left
      = "#{session[:b_dato].beginning_of_week.strftime('%-d. %b')} - #{session[:b_dato].end_of_week.strftime('%-d. %b')} (Uge #{session[:b_dato].cweek})"
    .pull-right
      = link_to admin_resource_path(@room, :b_dato => "#{session[:prev]}"), :class => "btn btn-default" do
        %i.fa.fa-angle-left
        = "Uge #{session[:prev].cweek}"
      = link_to admin_resource_path(@room, :b_dato => "#{session[:next]}"), :class => "btn btn-default" do
        = "Uge #{session[:next].cweek}"
        %i.fa.fa-angle-right
    .clearfix
    %hr/
    .row
      - @weekdays.keys.each do |weekday|
        .col-md-3
          %strong.weekday= @weekdays[weekday]
          - @room.timeslots.order(starttime: :asc).each do |timeslot|
            - if timeslot.startdate.cweek == @show_week
              - if timeslot.startdate.wday == weekday
                = link_to toggle_booking_admin_resource_timeslot_path(@room, timeslot), :method => :put do
                  - if timeslot.booked == true
                    .well.well-sm.well-timeslot.well-booked
                      %p
                        %strong.pull-left= timeslot.starttime.strftime("%H:%M")
                      .clearfix
                      %p
                        %small
                          .pull-left= timeslot.owner_first_name
                          .pull-right.badge
                            - if timeslot.is_recurring
                              %i.fa.fa-lock
                            - else
                              = timeslot.score
                      .clearfix
                  - else                    
                    .well.well-sm.well-timeslot{ :class => ( timeslot.bookings.count > 0 ? 'well-active' : '' ) }
                      %p
                        %strong.pull-left= timeslot.starttime.strftime("%H:%M")
                        - if timeslot.bookings.present?
                          %small.pull-right Byd
                      .clearfix

                      - unless timeslot.bookings.present?
                        %p
                          %small.pull-left Fri
                        .clearfix
                      - if timeslot.bookings.present?
                        %small
                          .pull-left= timeslot.owner_first_name
                          .pull-right.badge= timeslot.score
                        .clearfix