config/routes.rb
Tinkuy::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  mount Koudoku::Engine, at: 'members'
  scope module: 'koudoku' do
    get 'membership' => 'subscriptions#index', as: 'membership'
  end

  namespace :admin do
    get '/' => 'events#index'
    resources :users do
      get '/delete_subscription' => "users#delete_subscription"
    end
    resources :events
    resources :plans
    resources :centers
    resources :memberships
    resources :resources do
      resources :timeslots do
        member do
          put :toggle_booking
        end
      end
    end

  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    get '/events' => "users#events"
    get '/display_therapist' => "users#display_therapist"
  end

  resources :resources do
    resources :timeslots do
      resources :bookings
    end
  end

  resources :recurring_bookings

  resources :events do
    member {
      post :upvote
    }
  end

  get '/suggestions' => 'events#suggestions'

  get '/info' => 'pages#info'
  get '/faq' => 'pages#faq'
  get '/bliv_medlem' => 'pages#bliv_medlem'

  namespace :api do
    resources :users
  end

  root :to => "pages#bliv_medlem"

end

app/views/resources/_sidebar.html.haml
.well
  %h4 Book et rum
  %hr/
  %p Brug dine frugter til at booke et rum
  %p
    Ethvert frit rum kan sikres med
    %span.badge 5
    frugter inden for de nærmeste 7 dage
  %p
    Herudover kan ethvert rum sikres med 
    %span.badge 50
    frugter
  %hr/
  
  %h4 Hvordan booker du?
  %hr/
  %p Klik på feltet/tiden du gerne vil booke (i rummets kalender til venstre).
  %p Sæt dernæst frugter på.
  %p Se nedenfor hvordan du kan se om tiden kan bookes

  .well.well-sm.well-timeslot.well-explain
    %p 
      Fri 
      %br/
      %em kan bookes
  .well.well-sm.well-timeslot.well-active.well-explain
    %p 
      Lagt billet ind med
      %span.badge x
      frugter. 
      %br/ 
      %em Du kan byde over
  .well.well-sm.well-timeslot.well-booked.well-explain
    %p 
      Taget
      %br/
      %em 
        kan 
        %strong ikke
        bookes

app/views/resources/_top.html.haml
%p
  .pull-right= link_to "Til toppen", "#top"
  .clearfix
%hr/

app/views/resources/index.html.haml
.jumbotron.page
  .container
    .row
      .col-md-12
        %h1.page
          Book rum

.container
  .row
    .col-md-8
      %h3.header
        Du kan booke de følgende 
        = @rooms.length
        rum
      %hr/
      - for room in @rooms 
        = link_to room do
          .well.well-resource
            %h4= room.name
            %p= room.description


      %hr/
      %h3.header#top
        Vejledning
      %ul.list-unstyled
        %li= link_to "What is Tinkuy’s Therapy Room", "#what"
        %li= link_to "Who can book the Therapy Room?", "#who"
        -# %li= link_to "Payment/Rent", "#payment"
        %li= link_to "How to make a booking?", "#booking"
        %li= link_to "Short Guidelines when using the Therapy Room", "#guidelines"
        %li= link_to "FAQ by our Therapists", "#faq"
      %hr/

      %h3#what What is Tinkuy’s Therapy Room
      %p
        The Therapy Room is a a space within Tinkuy that offers the privacy, quiet and safe environment conducive to holding individual sessions and treatments. We want to make this space available to therapists with different backgrounds who offer sessions aimed at bringing healing and a more harmonious way of being.
      = render :partial => 'top'

      %h3#who Who can book the Therapy Room?
      %p
        The use of the Therapy Room is made available to our active members.
        If you’re not a member yet, you can sign up 
        %a{:href => "/membership"} 
          here.
      = render :partial => 'top'

      -# %h3#payment Payment/Rent
      -# %p
      -#   If you wish to rent the space and you’re not a shareholder/investor in Tinkuy, we ask you for a one time deposit of 500dkk.
      
      -# %h5 Regular Therapists
      -# %p
      -#   Therapists who book a fixed number of hours every week, pay the rent at the end of the month based on the income they generated. Meaning, we ask for a minimum of 25dkk/hour. This minimum is set in place to protect our regular therapists in case they don’t have any bookings from their own clients during their regular time slot.  
      -# %p
      -#   However, we ask each therapist to consider setting aside 10% of their asking rate per hour. Example, if you charge 700dkk per session, we ask you to set aside 70dkk for Tinkuy. At the end of the day, based on your number of treated clients and generated income, you can make an estimate of your contribution for the monthly rent. 
      -# %br/
      -# = render :partial => 'top'

      %h3#booking How to make a booking?
      %p
        Go to 
        = link_to "Book rum", resources_path
        and pick the room you want to book. You can make bookings by clicking the Timeslot for which you would like the room.
      = render :partial => 'top'

      %h3#guidelines Short Guidelines when using the Therapy Room
      %ul
        %li Make sure to leave the room on time.
        %li Leave the space, clean, tidy, ready to use. 
        %li Please remember to take any personal items with you.
        %li Shortly air out the room before you leave.
      %p
        If you have any comments in regards to how the room was found upon your arrival, or you have any special requirements, please contact Johan on johan@tinkuy.dk or at the center.
      = render :partial => 'top'

      %h3#faq FAQ by our Therapists
      %h5 What is provided in the Room and on the premises?
      %p
        The Therapy Room is freshly refurbished and currently is equipped with a massage table, a desk and two chairs.
      %p
        When using the Therapy Room you have access to the kitchen, bathroom and toilet rooms.

      %br/
      %h5 What is not provided and what should I bring?
      %p
        For the time being, we kindly ask you to think about bringing additional items you might need, such as bed sheets, towels or any other items you might need for your treatment. 

      %br/
      %h5 Is it allowed to do Aromatherapy, use oils, candles etc?
      %p
        It is allowed to use Aromatherapy on Wednesday, Thursday and Friday.
      %p
        Oils are of course allowed, but we ask you to protect the bed and furniture and to be mindful about the overall look and feeling of the room since it is used by many therapists and different clients, hygiene and cleanliness are of the outmost importance.
      %p
        Candles are allowed as long as you are present inside the room. Please make sure you put them all out before you leave the room, regardless of whether another therapist is using it just after you.

      %br/
      %h5 How often can I use the therapy room?
      %p
        The therapy room is being shared by several therapists, 5 of which have booked regular time frames every week. However, despite that, the schedule has many openings for basic members and weekend members.
      %p
        You are most welcome to apply for a regular use of the room. 
        We have two kinds of memberships for therapists - Extended and Professional
        If interested, 
        = link_to "send us an email", "mailto:tinkuy.therapy@gmail.com" 
        with an introduction about yourself and your activity, as well as the day of week and the number of hours you’d like to book


    .col-md-4
      = render :partial => 'sidebar'

app/views/resources/show.html.haml
.jumbotron.page
  .container
    .row
      .col-md-12
        %h1.page
          Book
          = @room.name

.container
  .row
    .col-md-8
      %h4.pull-left
        = "#{session[:b_dato].beginning_of_week.strftime('%-d. %b')} - #{session[:b_dato].end_of_week.strftime('%-d. %b')} (Uge #{session[:b_dato].cweek})"
      .pull-right
        = link_to resource_path(@room, :b_dato => "#{session[:prev]}"), :class => "btn btn-default" do
          %i.fa.fa-angle-left
          = "Uge #{session[:prev].cweek}"
        = link_to resource_path(@room, :b_dato => "#{session[:next]}"), :class => "btn btn-default" do
          = "Uge #{session[:next].cweek}"
          %i.fa.fa-angle-right
      .clearfix
      %hr/
      .row
        - @weekdays.keys.each do |weekday|
          .col-md-3
            %strong.weekday= @weekdays[weekday]
            - @room.timeslots.order(starttime: :asc).each do |timeslot|
              - if timeslot.startdate.cweek == @show_week
                - if timeslot.startdate.wday == weekday
                  - if timeslot.booked == true
                    .well.well-sm.well-timeslot.well-booked
                      %p
                        %strong.pull-left= timeslot.starttime.strftime("%H:%M")
                        - if timeslot.owner == current_user
                          %small.pull-right 
                            - if timeslot.is_recurring
                              = link_to "Slet", recurring_booking_path(timeslot.recurring_booking, :from_time => timeslot.startdate, :b_dato => timeslot.startdate.beginning_of_week),:confirm => "Vil du slette din faste booking fra #{timeslot.startdate.strftime('%-d/%-m')} og frem?", :method => :delete
                            - else  
                              = link_to "Slet", resource_timeslot_booking_path(@room, timeslot, timeslot.current_booking), :confirm => "Vil du slette dit bud?", :method => :delete
                      .clearfix
                      %p
                        %small
                          .pull-left= timeslot.owner_first_name
                          .pull-right.badge
                            / TODO: old way... we need to include better check
                            - if timeslot.is_recurring
                              %i.fa.fa-lock
                            - else
                              
                              = timeslot.score
                      .clearfix
                  - else
                    - if timeslot.can_be_booked
                      = link_to new_resource_timeslot_booking_path(@room, timeslot) do
                        .well.well-sm.well-timeslot{ :class => ( timeslot.bookings.count > 0 ? 'well-active' : '' ) }
                          %p
                            %strong.pull-left= timeslot.starttime.strftime("%H:%M")
                            - if timeslot.bookings.present?
                              %small.pull-right.blue Byd
                          .clearfix

                          - unless timeslot.bookings.present?
                            %p
                              %small.pull-left.blue Fri
                            .clearfix
                          - if timeslot.bookings.present?
                            %small
                              .pull-left= timeslot.owner_first_name
                              .pull-right.badge= timeslot.score
                            .clearfix
                    - else 
                      .well.well-sm.well-timeslot.well-booked        
                        %p
                          %strong.pull-left= timeslot.starttime.strftime("%H:%M")
                          - if timeslot.bookings.present?
                            %small.pull-right.blue Byd
                        .clearfix

                        - unless timeslot.bookings.present?
                          %p
                            %small.pull-left.blue Fri
                          .clearfix
                        - if timeslot.bookings.present?
                          %small
                            .pull-left= timeslot.owner_first_name
                            .pull-right.badge= timeslot.score
                          .clearfix

    .col-md-4
      = render :partial => 'sidebar'